### ISSUE TITLE
CycleNumber.csv moved to Done after failed payment

### ISSUE THREAD

**Issue by Xa52c** [tezos-reward-distributor-organization/tezos-reward-distributor#149]
Hot wallet contains no funds.
Launch TRD as a service.
It runs to make a payment for cycle number X.
No payment is made (hot wallet empty).
File X.csv gets put into Done.
Transfer funds to hot wallet.
TRD does not retry failed payment.

**Comment by jdsika** [comment]
Thank you reporting. We will look into it!

**Comment by amzid** [comment]
Probably what happened here is that the TRD injected the block and did not get any feedback. After a timeout, the transactions are marked as INJECTED and put under done.

The solution here is to correctly parse the output of the payout simulations in order to prevent operation injection in case the simulation (run_operation or preapply) was not successful. In fact, in case of insufficient funds, the run_operation rpc command returns a failure of the operation. We will analyze the reason why this failure is not successfully detected by TRD.

Thank you for reporting the issue.

**Comment by amzid** [comment]
This issue was reformulated in #220 and is solved by #251. Feel free to reopen the issue if needed.
