### ISSUE TITLE
Compensate delegators for missed endorsements/bakings

### ISSUE THREAD

**Issue by chiptus** [tezos-reward-distributor-organization/tezos-reward-distributor#204]
**Is your feature request related to a problem? Please describe.**
As a baker, I want to compensate my delegators for missed blocks.

**Describe the solution you'd like**
I think that a boolean config would be great to indicate if I'm paying for missed blocks. We can take it another step and supply percent, to indicate how much of the missed payment I want to pay, e.g for each missed endorsement I would pay 1tz instead of 2

**Describe alternatives you've considered**
I'm considering writing an external script to do that, but then it will be left out of the CSV files. A single solution for the whole process is what I'm looking for.

**Comment by utdrmac** [comment]
@chiptus The problem with implementing such a feature is that it would require TRD to be aware of all baking/endorsing rights for a particular baker.
`/chains/main/blocks/head/helpers/endorsing_rights` and `/baking_rights` are very CPU intensive RPC calls and most public RPC providers block these endpoints. I believe that this would force anyone wanting this payout methodology to have a local archive node.

This could be implemented as a basic option to TRD in how you pay as a baker: A) We pay actual rewards, or B) We pay idealized rewards.  A is how TRD functions today. B could be implemented by making the above RPC calls and doing all rewards calculations based off network constants (since the reward is now variable in Carthage) and then divided up as normal.

I'll put this in our list of features for consideration.
