### ISSUE TITLE
Investigate why CLI access to tezos-client is required (Kiln Support)

### ISSUE THREAD

**Issue by MHULT** [tezos-reward-distributor-organization/tezos-reward-distributor#247]
Hey guys,

Has someone got TRD working together with Kiln?

If so... how?

Best regards,
M

**Comment by utdrmac** [comment]
Unfortunately, due to the way Kiln hides all of the tezos binaries, it is currently not possible to make them work together. There is an open kiln issue on this: https://gitlab.com/obsidian.systems/kiln/issues/16
There are some crazy-hacky workarounds in that issue if you want to take a stab at it.

Will leave this issue open as FR into researching what TRD really needs and whether or not accessing the binaries is critical.

**Comment by jdsika** [comment]
@utdrmac is my assumtion correct, that the RPC is left open on the standard port and localhost for kiln so that the removal of the tezos binary dependency would solve this issue?

**Comment by utdrmac** [comment]
@jdsika That is my understanding yes.

**Comment by jdsika** [comment]
@amzid I am assigning you, as it is a synergy for planned work automatically solved with "removing the tezos binary dependency". Label has been changed to "blocked" only.
