### ISSUE TITLE
Should verbose mode output to stdout? (continued)

### ISSUE THREAD

**Issue by utdrmac** [tezos-reward-distributor-organization/tezos-reward-distributor#255]
Right now, when using `-V`, the stdout information remains the same. If you want to see the additional verbose messages  you  have to look in app.log. This is atypical of most CLI-based programs. With most GNU apps, as you increase `-v`, the output to stdout increases.  This would help users copy/paste more easily to slack/github as well vs.  having to upload a log file each time.

Thoughts?

**Comment by jdsika** [comment]
And there should be an option --log "filename"    default:app.log ?

**Comment by utdrmac** [comment]
> And there should be an option --log "filename" default:app.log ?

Probably, yes. To get even fancier, we can give the option to log to syslog, for those that run TRD as a service.

**Comment by jdsika** [comment]
Agree, let's do this in the next release

**Comment by habanoz** [comment]
My comments for each proposal is given below:

- Should verbose mode output to stdout?
In early versions, TRD used to print verbose output to stdout. However, the vast number of log lines generated in verbose mode makes stdout untrackable. It was not easy to copy-paste from the terminal window due to long output.  Eventually, I decided to direct verbose output to log file where it is easier to track using terminal commands like more, less, vi ... 

- And there should be an option --log "filename" default:app.log ?
I cannot see any added value here. Please help me see. It is necessary to let users determine log file names in cases where multiple applications can generate log into a common directory.

- To get even fancier, we can give the option to log to syslog, for those that run TRD as a service.
Currently in service mode application ouput can be traced using journalctl command with fine details. 

I believe the set of options provided should be limited to those generate real value. Increasing number of options may create unnecessary complexity which slowly leads to creating an unmanageable monster :)

Regards

**Comment by habanoz** [comment]
@utdrmac 
@jdsika 

What is your current view on this issue?

**Comment by utdrmac** [comment]
For me, as a TRD developer, having debug info on stdout is required. It kills my work flow to page through app.log looking for what I need to debug/understand. Having everything on stdout is so much easier.

For regular users, they don't need to see so much output. So the verbose option is good. However, when a user comes to me and says there's a problem, I must always ask them to re-run with verbose mode and then upload their log file, rather than just copy/paste stdout (which includes debug logs).

Most CLI-based apps work where adding -v increases the output onto stdout, so this is the behavior I'm expecting. I expect -V to affect both stdout and app.log.

I certainly agree that we should add --syslog as an option.

**Comment by habanoz** [comment]
@utdrmac 

>Most CLI-based apps work where adding -v increases the output onto stdout, so this is the behavior I'm expecting. I expect -V to affect both stdout and app.log.

I would argue that copying a very long terminal output is harder than copying a file. 

> I certainly agree that we should add --syslog as an option.

OK

**Comment by jdsika** [comment]
I will have a call with Ahmed tomorrow and write a consolidated opinion in here afterwards

**Comment by jdsika** [comment]
A minor cleanup has been merged. This is a copy of the further desired features coming for the next release.

> Huseyin Abanoz, [11.11.20 12:24]
> We can have two files. 1 app.log and app_verbose.log. app.log is the current log file.
> 
> Huseyin Abanoz, [11.11.20 12:25]
> app_verbose.log file keeps verbose logs. It rotates after each payout. Previous app_verbose is archived and kept for a while until it is completely deleted.
> 
> Huseyin Abanoz, [11.11.20 12:25]
> Also app_verbose log file name may include cycle number
> 
> Huseyin Abanoz, [11.11.20 12:27]
> Verbose switch may be used to turn on/off the app_verbose.log file, default value may be true so that  only experienced users can turn it off.
> 
> Huseyin Abanoz, [11.11.20 12:27]
> The behaviour I believe should be the same in all modes.
> 
> Huseyin Abanoz, [11.11.20 12:31]
> Last app_verbose file is not zipped until a new cycle starts, this way last app_verbose_file can be read easily, as Ahmet suggested.

**Comment by habanoz** [comment]
- Verbose output is controlled by -V,--verbose option. It can either be 'on' or 'off'. The default value is 'on', so that new users can collect verbose information in case they experience problems. Experienced users are recommended to turn verbose logging off by setting '-V off' option.

- Verbose log files are created in the logging directory, near the app log file. Verbose logfile names are named in the form of 'app_verbose_{cycle}_%Y%M%D_%H%m%s.log'. At application launch, since no payment cycle is selected, the verbose logging file name is in the form of 'app_verbose_init_%Y%M%D_%H%m%s.log'.

- Old verbose logging files are moved to the 'verbose_backup' folder which is created inside the logging directory. At most 60 backup files are stored. Backup files are kept in zip files to reduce disk usage.

- If a user experiences a problem and needs support he is required to provide 2 verbose logging files. First is the init verbose file which is probably moved to 'verbose_backup' folder and contains detailed information about the application launch. Second is the latest verbose log file which has detailed information for the current cycle.
