### ISSUE TITLE
Preparation for new Grant Proposal

### ISSUE THREAD

**Issue by jdsika** [tezos-reward-distributor-organization/tezos-reward-distributor#400]
Dear community,

[Link to the proposal](https://docs.google.com/document/d/1zIZquO1nLAy78RG8mWUgoBK9Cm7tUoNotDnwYX8V5LQ/edit?usp=drivesdk)

currently we own around 4500 XTZ in our multi signature [contract](KT1THuigzD2JUb31w9BpCiUo69dnuUUG58QY). At the time of writing this corresponds to 19800$ which is quite enough to last for the next months asking my gut. But let us make a little forward calculation in order to see why we need to act swiftly:
With the onboarding of @vkresch I can estimate ~10h/week from him which would add up to 10k$ in the next 4 months if his whole capacity is used. I think there is A LOT to do for TRD not only regarding feature requests but also regarding the stability of the tool. I would estimate a litte more conservative for @amzid as he is rather busy but let us assume he will make 5h /week which makes 5k$. Now it is getting thin up there and we just talked about half of the maintainers :)

I think we should gather ideas for improvements that we would put into another grant proposal. Create a common drive dokument, and set ourselves a deadline for end of April. Estimating a duration of 3 months for the response I think we are quite safe that the project can continue succesfully. I will start with some points:
.- Hire a specialist company for a security audit of the tool. Those are external costs, let us narrow down some names and think about the prerequisits for this. I think we are handling enough money here to justify an audit also considering that I want the unattended mode to run just perfectly. Remeber the slogan is "Run & Forget".
- I think we can improve the accounting system with a plugin style system to extract the information within the database (todo) in the manner the customer wants it
- Write a proper API for querying the DB and give it a versioning
- Improve the surveilance system of TRD
- support the next protocol upgrades (especially baking-accounts which might be quite some work)

I leave this as a starter :)

**Comment by vkresch** [comment]
From the quality perspective I would suggest enabling trd as a pip package so that users could just `pip install trd` or `pip install tezos-reward-distributor`. Then the [usage documentation](https://tezos-reward-distributor-organization.github.io/tezos-reward-distributor/run.html#command-line-usage) could be used not with:
```
python3 src/main.py -V on
python3 src/main.py -C 300 -P tzstats -M 4 -V on -D
```
but for example with:
```
trd -V on
trd -C 300 -P tzstats -M 4 -V on -D
```
The deployment to pip would be implemented via github-actions. I also liked the idea from @habanoz of an optional GUI support (https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/issues/342) which is just an optional extension of the cli interface which is built on top of it and would be completly separate of the `trd-cli` and could be started with `trd-gui` for example. I could contribute with [pyQt](https://en.wikipedia.org/wiki/PyQt) knowledge to that.

I'm not sure on which platform the current trd users are running trd but maybe macOS and windows support could increase the user size thus making sure to cover these platforms with documentation and tests in the CI.

**Comment by utdrmac** [comment]
I like the idea of the pip package.

I disagree that the GUI should be a separate process. Like most, if not all, CLI/GUI apps, the GUI is built-in and enabled/disable with a simple flag. Even if you make it a separate process, how does this process get information from the core trd? There would still need to be an API of sorts for communication between them and if you're going to do that, you might as well just write all that into the core trd instead of having to duplicate effort.

**Comment by utdrmac** [comment]
TRD already works on mac and windows with appropriate python installed. What more are you looking for? By having the GUI be web-based, you don't have to code anything mac or windows specific either. An extremely simple React app would work wonders here.

**Comment by habanoz** [comment]
I agree, using pip would be more user-friendly.

**Comment by nicolasochem** [comment]
It's grant season. I suggest we submit an application sooner than later. I don't think we need to list improvements, especially if it will drag the process down. We should say something like:

> While other DPoS blockchains have the reward payout feature built-in the protocol code, tezos has elected to leave this responsibility to the bakers. A well-designed and well-maintained piece of payout software is essential to maintain the trust relationship between bakers and their delegators.
> 
> TRD is the dominant piece of software for reward payout. The Tezos protocol is dynamic and fast-evolving. The Granada protocol changed the protocol constants, which required significant upgrades to TRD. Everyone in the TRD team is contributing on spare time, which brings challenges.
> 
> Significant work on TRD is anticipated due to:
> 
> * the migration to tenderbake which will change the reward calculation mechanism once more
> * increased use of smart contract delegation which brings more variance in the payout behavior
> 
> The existing TRD team has proven itself to be dynamic and adaptable, however the rate of contributions is currently too low. It is essential that the team be funded appropriately to keep this pillar of the ecosystem standing and functional.
>
