### ISSUE TITLE
tests should not depend on external apis being up

### ISSUE THREAD

**Issue by nicolasochem** [tezos-reward-distributor-organization/tezos-reward-distributor#421]
CI tests appear broken now. Tests should run in isolation IMO. Have you considered recording and replaying API calls from external RPC services (RPC, tzstats, tzkt), for example like this:

https://www.mock-server.com/proxy/record_and_replay.html

**Comment by nicolasochem** [comment]
or this https://dev.to/meeshkan/create-a-mock-server-for-any-rest-api-592l

**Comment by vkresch** [comment]
@nicolasochem thanks for reporting. I'm currently working on the PR to validate baking addresses in which I fix the current error. The reason for the current error is the recent removal of the `https://api.carthage.tzkt.io/v1/ `domain name. 

IMO it's always good to test the trd functions against the real API so that the regression tests are always up to date and detect compatibility issues between trd and the API on which it depends. When a test fails it means either the test or the function which it tests needs to be fixed which is a good process for the improvement of trd. Let's hear other opinions, too.

**Comment by jdsika** [comment]
Using recorded api calls is on my wish list for over 1 year now - Viktor has just started and will go towards this task! Important, thank you for also noticing :)
