### ISSUE TITLE
dry-run writes a csv file in "done" folder while no payout was done

### ISSUE THREAD

**Issue by nicolasochem** [tezos-reward-distributor-organization/tezos-reward-distributor#498]
Dry-run should not write a "done" file since no payment was done. ~With defaults params, it appears to be the case.~

~It has been speculated on slack that when using a custom reports directory, dry runs write a report as if it was really paid out.~

Can anyone confirm or point to the code where this may be happening?

**Comment by baketzforme** [comment]
I'm not very familiar with the codebase, but I have experienced reports being written when doing a dry-run. I think the issue be found here:

https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/blob/e6ae93306de02cb11d12ab363df5d9f1fb7194d9/src/pay/payment_consumer.py#L125-L126

This function does not appear to take into account whether TRD is running in Dry Run mode or not.

It uses this function to determine the path:

https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor/blob/e6ae93306de02cb11d12ab363df5d9f1fb7194d9/src/util/dir_utils.py#L14-L15

Which as far as I can tell, also does not account for Dry Run.

**Comment by nicolasochem** [comment]
I just tried with the default directory and it seems that even then it's writing to the "done" folder. So it's not dependent on whether or not the default directory is being used.

**Comment by jdsika** [comment]
I see the issue in the following lines: bakin_dirs.py
```

class BakingDirs:
    def __init__(self, args, baking_address) -> None:
        super().__init__()

        # 7- get reporting directories
        reports_base = os.path.expanduser(args.reports_base)

        # if in reports run mode, do not create consumers
        # create reports in reports directory
        if args.dry_run:
            reports_base = os.path.expanduser("./reports")
```

1) First of all the comment should say "if in dry-run mode [...]"
2) -r lets you state a directory for the reports.
3) if in dry-run this directory is simply overwritten with "./reports" without a notice

We have the following problems:
1) A user is not able to distiguish between a directory with reports that are executed or only simulated as one directory starts with "pymnt" and the other has to prefix. Apart from the fact that the prefix should be "payments" and not this kind of strange abbreviation, the dry-run directory should have e.g. the prefix "simulations"
2) If a user sets "-r ./reports" then we cannot distiguish the simulation from the actual payments anymore.

Solution:
With regard to a potential Windows compatibility from #553 I recommend to set the default path of the reports directory to "./" which is the intuitive place anyway. The help section should inform the user that there are two subfolders. A renamed "payments" folder and a "simulations" folder. The code above should add a suffix to "./" and expand the reports_base with either "payments" or "simulations" depending on "args_dry_run == True"


@nicolasochem Would you agree with this approach and do you see any issues here. Bear in mind that a lot people use the reports from the simulations for a lot of purposes and they need to be written.

**Comment by nicolasochem** [comment]
```
reports
└── tz1xxx
    ├── calculations
    │   └── 449.csv
    └── payments
        ├── done
        │   └── 449.csv
        └── failed
            └── 449.csv
```

We already have 2 subfolders, `calculations` and `pyaments` for baker.

Are you suggesting the following?

```
reports
└── tz1xx
    ├── calculations
    │   └── 449.csv
    ├── payments
    │   ├── done
    │   │   └── 449.csv
    │   └── failed
    │       └── 449.csv
    └── simulations
        ├── done
        │   └── 449.csv
        └── failed
            └── 449.csv
```

The above would be OK to me.

**Comment by jdsika** [comment]
On a second note I would go for `../ `as the default base path to make sure that deleting the TRD repository folder or using something like `git clean -dxf ` does not delete the reports.
The calculations that come along with a payment are also a docmument that should not be overwritten, as it was created at the time of the payment - it could change with changes in TRD or varying API returns.  It is kind of dangerous to change the default path because TRD looks at the reports to evaluate what cycles are already paid out. As I think about it changing the default path without a safety mechanism is dangerous regarding the backwards compatibility. What do we need - Including a discussion about the renaming of the directories?

1) Change the following default parameter:
`--config_dir ~/pymnt/cfg `   &rarr; delete this optional argument
`--reports_base ../trd-data/` &rarr; Here we need to make the change! Extend the help section the following way:

> 
> The base path for all TRD data. The directory contains the following folders:
> 1) $REPORTS_BASE/configurations
> 2) $REPORTS_BASE/simulations
> 3) $REPORTS_BASE/reports
> Attention: Please make sure you have migrated the data accordingly after upgrading to v11

2) This would result in the following structure:

```
trd-data
└──configurations
    └── tz1xx.yaml
└──simulations
    └── tz1xxx
       ├── calculations
       │   └── 449.csv
       └── payments
           ├── done
               └── 449.csv (The status indicated a simulation)
└──reports
    └── tz1xxx
       ├── calculations
       │   └── 449.csv
       └── payments
           ├── done
           │   └── 449.csv
           └── failed
               └── 449.csv
```

3) As a safety mechanism it could suffice that TRD does not find the configuration anymore. We give the user a message that he should use the --help section, create the base structure of the folders above if not already existend and the user migrates the data.

**Comment by jdsika** [comment]
That is not necessarily true as the simulation can be re-run at a later time with a new version of TRD or changing values in the API. The calculation file created with the exact version of TRD and at the same time which was the basis for the payment needs to be stored

**Comment by nicolasochem** [comment]
ok

**Comment by jdsika** [comment]
In the morning I started a PR. You can have a first look at it.
