### ISSUE TITLE
Use TRD in dryrun without signer

### ISSUE THREAD

**Issue by redref** [tezos-reward-distributor-organization/tezos-reward-distributor#614]
**Description**
When using TRD in dryrun mode, signer configuration is still required to validate `payment address`.

**To Reproduce**
Start TRD in dryrun without signer started or configured with payment address key.

**Expected behavior**
Should compute payments and stats without halting.

**Environment**
 - Docker / K8S
 - testnet
 - `python src/main.py --network GHOSTNET --base_directory /var/run/tezos/trdconfig --reward_data_provider tzkt --signer_endpoint http://127.0.0.1:6732 --node_endpoint <endpoint> --docker --dry_run --payment_offset 20 --release_override 0`
 - Alpine 3.16

**Comment by nicolasochem** [comment]
First and most importantly: thank you for this contribution.

I missed the train on this one but it's important to test signing when in dry-run mode.

Signing can go wrong for a variety of reasons, tezos has many different signer implementations, so it is really important for dry run to test the entire stack, which includes signing, and stop right before injection.

Arguably it's dangerous to sign operations because they can be replayed later. And the original issue is valid: when trying payouts with ledger for example, it's annoying to have to plug it, unlock it, just to try payouts.

Can we sign by default in dry-run and have a `--dry-run-no-signing` flag?

**Comment by redref** [comment]
I tend to agree with you on the "dryrun should sign and drop before injection".

On the other end, modification was only about checking key exists in signer. Signature was and is not actually done in dryrun mode.

I am not sure I can handle modifications to do so.
