### ISSUE TITLE
Latest version doesn't respect `reports_base`

### ISSUE THREAD

**Issue by nurikabe** [tezos-reward-distributor-organization/tezos-reward-distributor#94]
**Describe the bug**

Reports base is `~/pymnt/reports`:

```
2019-06-28 11:01:22,169 - MainThread - Arguments Configuration = {
 "network": "MAINNET",
 "reward_data_provider": "tzscan",
 "reports_base": "~/pymnt/reports",
```

Yet report directory is being recreated in the current working directory:

```
2019-06-28 11:01:37,533 - producer  - Calculation report is created at '/home/tezos/tezos-reward-distributor/reports/tz1MQJPGNMijnXnVoBENFz9rUhaPt3S7rWoz/calculations/112.csv'
```

**Expected behavior**

`reports_base` should be scanned for existing reports and new reports should be deposited here accordingly.

**Environment**
 - Source, `TRD version 5.7 is running in interactive mode`
 - mainnet
 - `python3 src/main.py -C 112 -M3 -D`

**Additional context**

Glad I ran this in dry run mode.. Could have ended up duplicating a bunch of payments.

**Comment by habanoz** [comment]
In dry mode, "report base" is under trd folder. This is required to avoid generating fake reports under actual reports directory. Maybe we should rename this folder as "tezos-reward-distributor/dry_reports" to avoid confusion. 

Since the first release, before doing any actual payments, TRD checks for existing reports.

**Comment by nurikabe** [comment]
What about putting them in "`reports_base`/dry"?  So the default would be "~/pymnt/reports/dry"

This would be more intuitive, at least for me.

**Comment by nurikabe** [comment]
Related: It's a little confusing that the dry run doesn't take exising reports into considering.  For example, if I already have a report for cycle 112, I would expect the dry run to notice this and skip.

Likewise, it would be nice if the output were a little more clear about dry run reports. For example, instead of:

```
Calculation report is created at '/home/tezos/tezos-reward-distributor/reports/tz1XYZ/calculations/112.csv'"
```

Maybe something like:

```
Dry run calculation report created at '/home/tezos/tezos-reward-distributor/reports/tz1XYZ/calculations/112.csv'"
```

**Comment by jdsika** [comment]
I actually see the issues #12 and #15 highly related to this one. Users are not clear on the reporting structure and are scared to use the tool related to the fear of double payments. We should really think about creating a proper reporting/DB structure in order to handle multiple baker adresses, create reports from dry runs and store the information about successfull payments. Those should also be validated against the information from the node. I propose to look at the [PyTezos](https://github.com/baking-bad/pytezos) documentation and verify the available features for the interaction with a node. I mean they are using it for BakingBad - it is a service for validating transactions?

**Comment by denver-s** [comment]
> In dry mode, "report base" is under trd folder. This is required to avoid generating fake reports under actual reports directory.

I was about to ask the same thing as @nurikabe, glad that I found this issue still open.

**Comment by utdrmac** [comment]
I'll admit, this one has caused me some issues in the past as well. I like the idea of creating the files like: `~/pymnts/reports/calculations/112_dryrun.csv`
The short/quick fix is the above filenames, the long fix is migration to database storage which is in progress
